// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Schedules.Microservice.Infrastructure.Database;

#nullable disable

namespace Schedules.Microservice.Migrations
{
    [DbContext(typeof(SchedulesDbContext))]
    [Migration("20250117215543_Update-Models")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InteractReef.Packets.Schedules.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrgId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("InteractReef.Packets.Schedules.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ScheduleIdDenominator")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduleIdNumerator")
                        .HasColumnType("integer");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleIdDenominator");

                    b.HasIndex("ScheduleIdNumerator");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("InteractReef.Packets.Schedules.SubjectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrgId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubjectItems");
                });

            modelBuilder.Entity("InteractReef.Packets.Schedules.ScheduleItem", b =>
                {
                    b.HasOne("InteractReef.Packets.Schedules.Schedule", null)
                        .WithMany("DenominatorWeek")
                        .HasForeignKey("ScheduleIdDenominator")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteractReef.Packets.Schedules.Schedule", null)
                        .WithMany("NumeratorWeek")
                        .HasForeignKey("ScheduleIdNumerator")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InteractReef.Packets.Schedules.Schedule", b =>
                {
                    b.Navigation("DenominatorWeek");

                    b.Navigation("NumeratorWeek");
                });
#pragma warning restore 612, 618
        }
    }
}
